package workflow

const (
	MSG_FLOW_CREATED                = "Flujo creado Tag:%s version:%s name:%s"
	MSG_FLOW_NOT_FOUND              = "Flujo no encontrado"
	MSG_FLOW_NOT_INSTANCE           = "Flujo no instanciado"
	MSG_START_WORKFLOW              = "Iniciando el workflow"
	MSG_INSTANCE_NOT_FOUND          = "Instancia no encontrada"
	MSG_INSTANCE_EXISTS             = "Instancia existe"
	MSG_INSTANCE_FAILED             = "Instancia fallido:%s Tag:%s status:%s, step:%d error:%s"
	MSG_INSTANCE_STATUS             = "Instancia:%s Tag:%s status:%s, step:%d"
	MSG_INSTANCE_DEBUG              = "Instancia:%s debug:%s"
	MSG_INSTANCE_GOTO               = "Instancia %s Tag:%s ir al step:%d mensaje:%s"
	MSG_INSTANCE_LOAD               = "Instancia load:%s tag:%s currentStep:%d"
	MSG_INSTANCE_ALREADY_DONE       = "Instancia ya finalizada"
	MSG_INSTANCE_ALREADY_RUNNING    = "Instancia ya en ejecucion"
	MSG_INSTANCE_PENDING            = "Instancia pendiente"
	MSG_INSTANCE_WORKFLOWS_IS_NIL   = "workFlows es nil"
	MSG_ID_REQUIRED                 = "id es requerido"
	MSG_INSTANCE_EXPRESSION_TRUE    = "Resultado de la expresion es true"
	MSG_INSTANCE_EXPRESSION_FALSE   = "Resultado de la expresion es false"
	MSG_INSTANCE_ROLLBACK           = "Esta intentando hacer rollback de un step que no existe"
	MSG_INSTANCE_ROLLBACK_STEP      = "haciendo rollback del step:%d"
	MSG_INSTANCE_STEP_CREATED       = "Step creado:%d name:%s Tag:%s"
	MSG_INSTANCE_ROLLBACK_CREATED   = "Rollback creado:%d name:%s Tag:%s"
	MSG_INSTANCE_ROLLBACK_FAILED    = "Rollback Instance:%s Tag:%s status:%s, step:%d error:%s"
	MSG_INSTANCE_CONSISTENCY        = "Consistencia definida Tag:%s consistency:%s"
	MSG_INSTANCE_RESILIENCE         = "Resilencia definida Tag:%s totalAttempts:%d timeAttempts:%s retentionTime:%s"
	MSG_INSTANCE_IFELSE             = "IfElse definido step:%d name:%s expresion:%s ? %d : %d Tag:%s"
	MSG_INSTANCE_RETENTION          = "Retencion definida Tag:%s retentionTime:%s"
	MSG_INSTANCE_GOTO_USER_DECISION = "Por desicion del usuario"
	MSG_WORKFLOW_DELETE             = "Workflow eliminado Tag:%s"
	MSG_WORKFLOW_DONE_INSTANCE      = "Instancia finalizada:%s"
	MSG_WORKFLOW_LIMIT_REQUESTS     = "Límite de peticiones alcanzado, el proceso se pondra en espera para ejecusión, instanceId:%s"
)
